# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Baby Height Predictor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'STPopup'

end
